// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNF_zUX66XsX3P3DvVKp_o7_aBBRnCt4',
    appId: '1:256338910456:web:97b748871eefa478a1ef0d',
    messagingSenderId: '256338910456',
    projectId: 'proyecto-iot-f18db',
    authDomain: 'proyecto-iot-f18db.firebaseapp.com',
    databaseURL: 'https://proyecto-iot-f18db-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-iot-f18db.appspot.com',
    measurementId: 'G-L8819HTHSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW9ikWn_ej54Q1kE_TgSbRqsh7JhHuYFk',
    appId: '1:256338910456:android:962144931a957991a1ef0d',
    messagingSenderId: '256338910456',
    projectId: 'proyecto-iot-f18db',
    databaseURL: 'https://proyecto-iot-f18db-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-iot-f18db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdo4W88pWS49xOLHNejmaIsVNNuDiJgEY',
    appId: '1:256338910456:ios:b094778f44650121a1ef0d',
    messagingSenderId: '256338910456',
    projectId: 'proyecto-iot-f18db',
    databaseURL: 'https://proyecto-iot-f18db-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-iot-f18db.appspot.com',
    iosBundleId: 'com.example.rooms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdo4W88pWS49xOLHNejmaIsVNNuDiJgEY',
    appId: '1:256338910456:ios:a1fd8cdd82db9817a1ef0d',
    messagingSenderId: '256338910456',
    projectId: 'proyecto-iot-f18db',
    databaseURL: 'https://proyecto-iot-f18db-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-iot-f18db.appspot.com',
    iosBundleId: 'com.example.rooms.RunnerTests',
  );
}
